name: Verify Front Modules

on:
  workflow_call:
      inputs:
        PATH:
          required: true
          type: string
          description: "Path to the module directory (e.g., apps/nugu)"
        NAME:
          required: true
          type: string
          description: "Module name for display"
          
jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: apps

    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: apps/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
            ${{ runner.os }}-turbo-

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
        cache-dependency-path: 'apps/pnpm-lock.yaml'

    - name: Install dependencies
      run: pnpm install

    - name: Run checks
      run: |
          pnpm turbo lint
          pnpm turbo typecheck  
          pnpm turbo test
          pnpm turbo build